### File I/O with arrays

In [2]:
import numpy as np

Comúnmente la lectura y escritura de archivos se realiza con Pandas, aunque eso no quiere decir que NumPy no tenga sus propios métodos para tal fin

El método **save** guarda por defecto todo el contenido binario bruto del array de manera no comprimida en un fichero ".npy" 

In [14]:
arr = np.random.randn(100)
np.save('array', arr)

In [8]:
arr

array([ 7.80706698e-03, -2.21566897e+00,  5.19044917e-01, -6.97796589e-02,
        2.13917814e-01, -1.28740458e+00, -1.47556483e+00,  1.82920484e+00,
       -3.63617121e-01,  5.45666243e-01,  1.21216830e+00,  6.46601735e-01,
        1.47539031e+00,  2.97353928e-01, -3.33216973e-03, -8.28872600e-01,
        2.87052592e+00, -3.08288842e-01, -6.42532967e-01,  3.88673956e-01,
        3.62810671e-01, -7.18589127e-02,  8.39105208e-01,  8.80832367e-01,
       -2.66393580e+00,  5.28833540e-02,  1.60616955e-01,  4.99402734e-01,
       -1.66954238e+00,  2.46787115e+00,  1.96832523e+00,  1.23358616e-01,
        6.45257767e-01,  1.36275521e+00, -7.22064198e-01,  1.22001963e+00,
       -3.50916127e-01, -4.64639415e-01, -8.04503300e-01,  1.74385844e+00,
       -7.29947689e-01,  1.96587384e-01,  1.19938539e+00,  1.69550849e+00,
        1.40276092e+00, -4.43996350e-01,  9.91738077e-04,  6.74997485e-02,
       -3.06364214e-01,  6.23470888e-01,  2.70167147e-01, -1.77675946e-01,
       -1.57850128e+00,  

El método **load** permite cargar el fichero

In [15]:
arr_loaded = np.load('array.npy')
arr_loaded

array([-0.37987056,  0.76854189,  0.82444374, -0.06091475, -0.13129477,
       -0.77473248,  0.54192218,  0.89088063,  1.04313292, -0.6712153 ,
       -3.07245139,  1.53520479, -2.01311564, -0.83586827, -0.52730693,
       -2.01415927, -0.70998249,  1.31181321,  1.06898267,  0.23974511,
        0.0078362 , -0.23199758, -0.99559013, -1.64362271,  0.00949328,
       -0.6416285 ,  1.21592359,  2.08599815, -2.08222589,  0.15712055,
       -0.43726339,  1.45322129, -1.38239154,  0.91474186, -0.85590403,
       -1.32409223, -0.56366181, -1.48518   ,  1.04795783, -0.87182915,
        1.36660499,  1.38664986, -0.65829194, -1.51469522,  0.98937576,
       -1.08252104, -0.27287721, -2.73757155,  0.5832606 ,  1.06606425,
        0.28949727, -0.59520675,  1.33712435, -0.82435392, -0.19929765,
       -2.49370521, -1.19944567,  0.57778453, -0.52299605, -0.56769532,
       -0.4474826 ,  0.85135111,  0.39352924,  1.34303397, -0.10547293,
       -0.48554099, -1.08714668, -0.76457641,  0.23355654, -1.75

El método **savez** permite guardar en disco más de un array, indicando cada uno de estos arrays con un keyword

In [20]:
arr_a, arr_b = np.arange(10000), np.arange(10000)

In [21]:
np.savez('two_arrays', a=arr_a, b=arr_b)

In [17]:
arrays = np.load('two_arrays.npz')
arrays

In [18]:
arrays['a'], arrays['b']

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177

En arrays con gran cantidad de datos, para poder comprimirlo mejor sería conveniente usar el método **savez_compressed**

In [19]:
arr_a1, arr_b1 = np.arange(10000), np.arange(10000)
np.savez_compressed('two_arrays_compressed', a=arr_a1, b=arr_b1)