### Linear Algebra

In [1]:
import numpy as np

In [7]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [3]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [5]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [6]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

**numpy.linalg** tiene un estandar de descomposición de matrices.

In [8]:
from numpy.linalg import inv, qr

In [11]:
X = np.random.randn(5, 5)
X

array([[-0.87473664,  1.26896741, -1.10685208,  0.45860229, -1.4867295 ],
       [-0.5105846 , -1.17462454, -0.26259882, -0.72568252, -1.19582404],
       [ 1.65255976,  0.83364177, -0.40942771, -2.25108942,  1.78837806],
       [ 0.09050498,  0.88566033, -2.19967804,  1.38747318, -1.61089405],
       [ 0.61169068, -0.54617997, -0.68051475, -1.34738547, -0.4927357 ]])

In [12]:
mat = X.T.dot(X)
mat

array([[ 4.13917121,  0.61343922, -0.18966711, -4.4493036 ,  4.41927196],
       [ 0.61343922,  4.76768648, -3.01390429,  1.5224986 , -0.14868294],
       [-0.18966711, -3.01390429,  6.76339451, -1.53046174,  5.10616225],
       [-4.4493036 ,  1.5224986 , -1.53046174,  9.54486418, -5.41099525],
       [ 4.41927196, -0.14868294,  5.10616225, -5.41099525,  9.67642393]])

In [13]:
inv(mat)

array([[ 15.40640437,   6.16738117,  13.83402046,   0.50155213,
        -13.96104225],
       [  6.16738117,   3.05528258,   6.03610661,  -0.02993803,
         -5.97166897],
       [ 13.83402046,   6.03610661,  13.10851185,   0.20087491,
        -13.03023603],
       [  0.50155213,  -0.02993803,   0.20087491,   0.27136778,
         -0.18377416],
       [-13.96104225,  -5.97166897, -13.03023603,  -0.18377416,
         13.16083879]])

In [14]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.11022302e-16,  0.00000000e+00],
       [ 4.44089210e-16,  1.00000000e+00,  3.55271368e-15,
         2.08166817e-17,  4.21884749e-15],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         1.11022302e-16, -1.42108547e-14],
       [ 0.00000000e+00,  0.00000000e+00,  1.42108547e-14,
         1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  7.10542736e-15,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00]])

In [15]:
q, r = qr(mat)

In [16]:
q

array([[-0.54886668, -0.12173877,  0.22613846, -0.54127995, -0.58292577],
       [-0.0813439 , -0.81430778, -0.33646377,  0.39358345, -0.24933953],
       [ 0.02515043,  0.51393878, -0.63835784,  0.17813238, -0.54406113],
       [ 0.58999117, -0.24062942, -0.35484935, -0.68412788, -0.00767326],
       [-0.58600889,  0.00684952, -0.54975881, -0.22879243,  0.54951428]])

In [17]:
r

array([[ -7.54130538,   0.18507068,  -3.37584836,  11.08201363,
        -11.1479843 ],
       [  0.        ,  -5.8733822 ,   6.3565552 ,  -3.81853117,
          3.57565527],
       [  0.        ,   0.        ,  -5.61036165,  -0.95368854,
         -5.60977608],
       [  0.        ,   0.        ,   0.        ,  -2.55698872,
         -0.05308939],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.04175374]])