### Linear Algebra

In [1]:
import numpy as np

In [6]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [7]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [9]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [11]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])