### Universal functions: Fast Element-Wise Array Functions

Se trata de funciones universales que ejecutan operaciones sobre los elementos de ndarrays.

In [3]:
import numpy as np

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.sqrt(arr)  # calcula la raíz cuadrada de cada elemento del ndarray

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
np.exp(arr)  # calcula el exponente de cada elemento del ndarray

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [16]:
x = np.random.rand(8)
y = np.random.rand(8)
print(x)
print(y)

[0.48001294 0.29562979 0.08489719 0.12959309 0.60788169 0.38123723
 0.49393664 0.58204171]
[0.33794496 0.81680816 0.64553902 0.26504375 0.52962811 0.63717294
 0.78053206 0.63433655]


In [18]:
np.maximum(x, y)  # compara ambos ndarray, y por cada una de las posiciones se queda con el elemento de mayor valor

array([0.48001294, 0.81680816, 0.64553902, 0.26504375, 0.60788169,
       0.63717294, 0.78053206, 0.63433655])

In [22]:
arr = np.random.rand(7) * 5
arr

array([3.04240867, 3.04704869, 1.80220228, 1.35678915, 3.42708371,
       4.40298581, 2.27037185])

In [24]:
np.modf(arr)

(array([0.04240867, 0.04704869, 0.80220228, 0.35678915, 0.42708371,
        0.40298581, 0.27037185]),
 array([3., 3., 1., 1., 3., 4., 2.]))

In [45]:
np.sqrt(arr, arr)  # al segundo parámetro le establece el valor del resultado del método

array([1.1492174 , 1.14943634, 1.07640434, 1.03887679, 1.16644855,
       1.20356184, 1.1079295 ])

In [46]:
arr

array([1.1492174 , 1.14943634, 1.07640434, 1.03887679, 1.16644855,
       1.20356184, 1.1079295 ])

In [48]:
np.sign(np.array([10, 0, 0, 5, -2]))  # evalua si es positivo (1), cero (0), o negativo (-1) cada uno de los elementos

array([ 1,  0,  0,  1, -1])

In [51]:
np.add(arr, arr)  # sumatorio por cada uno de los elementos de cada ndarray

array([2.2984348 , 2.29887268, 2.15280869, 2.07775359, 2.33289711,
       2.40712369, 2.21585899])

In [53]:
np.subtract(arr, arr)  # realiza la resta por cada uno de los elementos de cada ndarray

array([0., 0., 0., 0., 0., 0., 0.])