## NumPy ndarray

In [1]:
import numpy as np

In [2]:
data = np.random.rand(2, 3)
data

array([[0.46872136, 0.57626428, 0.30311731],
       [0.99837095, 0.03706662, 0.84955639]])

In [3]:
data * 10

array([[4.68721359, 5.76264278, 3.03117309],
       [9.98370953, 0.37066623, 8.49556393]])

In [4]:
data + data

array([[0.93744272, 1.15252856, 0.60623462],
       [1.99674191, 0.07413325, 1.69911279]])

Todos los elementos de un ndarray son del **mismo tipo**, es decir, se trata de un contenedor multidimensional totalmente homogéneo. El método shape indica los elementos y el tipo de dato que contiene.

In [7]:
data.shape  # muestra el tamaño de cada dimensión

(2, 3)

In [8]:
data.dtype  # muestra el tipo de dato que contiene el ndarray

dtype('float64')

#### Creando ndarrays

In [14]:
data1 = [1, 2, 3, 4, 5]
array1 = np.array(data1)  # creación a raíz de una lista
array1

array([1, 2, 3, 4, 5])

In [19]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
array2 = np.array(data2)  # creación a raíz de una lista de listas
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
print(array1.shape)
print(array2.ndim)
print(array2.shape)

(5,)
2
(2, 4)


In [28]:
print(np.zeros(10))  # ndarray de una dimensión con diez elementos '0'
print(np.zeros((5, 10)))  # ndarray de cinco dimensiones con 10 elementos '0' en cada dimensión

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [31]:
np.arange(10)  # ndarray de una dimensión con diez elementos (versión del método range() nativo de Python)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Tipos de datos en los ndarrays